package com.jd.help.service.impl;

import com.jd.common.web.result.Result;
import com.jd.help.dao.HotIssueDao;
import com.jd.help.domain.HotIssue;
import com.jd.help.service.HotIssueService;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;

/**
 * HotIssue service й╣ож
 * generated by bud
 *
 * @author @laichendong
 */
@Service("hotIssueService")
public class HotIssueServiceImpl implements HotIssueService {
    @Resource
    private HotIssueDao hotIssueDao;

    public Result list(HotIssue hotIssue, int page, int pageSize) {
        Result result = new Result();
        if (hotIssue == null) {
            return result;
        }
//        PaginatedList<HotIssue> hotIssueList = hotIssueDao.queryForList(hotIssue, page, pageSize);
//        result.setSuccess(true);
//        result.addDefaultModel("hotIssueList", hotIssueList);
        return result;
    }

    public Result detail(HotIssue hotIssue) {
        Result result = new Result();
        if (hotIssue == null) {
            return result;
        }
        result.setSuccess(true);
        hotIssue = hotIssueDao.queryForObject(hotIssue);
        if (hotIssue == null) {
            return result;
        }
        result.addDefaultModel("hotIssue", hotIssue);

        return result;
    }

    public Result insert(HotIssue hotIssue) {
        Result result = new Result();
        if (hotIssue == null) {
            result.setSuccess(false);
            result.setResultCode("system.no.entity.to.operate");
            return result;
        }
        Long id = hotIssueDao.insert(hotIssue);
        if (id <= 0) {
            result.setSuccess(false);
            result.setResultCode("system.insert.error");
        } else {
            result.setSuccess(true);
            result.setResultCode("system.insert.success");
        }
        return result;
    }

    public Result update(HotIssue hotIssue) {
        Result result = new Result();
        if (hotIssue == null || hotIssue.getId() == null || hotIssue.getId() <= 0) {
            result.setSuccess(false);
            result.setResultCode("system.no.entity.to.operate");
            return result;
        }
//        boolean success = hotIssueDao.update(hotIssue);
//        result.setSuccess(success);
//        if(success){
//            result.setResultCode("system.update.success");
//        } else {
//            result.setResultCode("system.update.success");
//        }
        return result;
    }

    public Result delete(HotIssue hotIssue) {
        Result result = new Result();
        if (hotIssue == null || hotIssue.getId() == null || hotIssue.getId() <= 0) {
            result.setSuccess(false);
            result.setResultCode("system.no.entity.to.operate");
            return result;
        }
//        boolean success = hotIssueDao.delete(hotIssue);
//        result.setSuccess(success);
//        if(success){
//            result.setResultCode("system.delete.success");
//        } else {
//            result.setResultCode("system.delete.error");
//        }
        return result;
    }
}
