package com.jd.help.service.impl;

import com.jd.common.web.result.Result;
import com.jd.help.dao.TempletDao;
import com.jd.help.domain.Templet;
import com.jd.help.service.TempletService;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;

/**
 * Templet service й╣ож
 * generated by bud
 *
 * @author @laichendong
 */
@Service("templetService")
public class TempletServiceImpl implements TempletService {
    @Resource
    private TempletDao templetDao;

    public Result list(Templet templet, int page, int pageSize) {
        Result result = new Result();
        if (templet == null) {
            return result;
        }
//        PaginatedList<Templet> templetList = templetDao.queryForList(templet, page, pageSize);
//        result.setSuccess(true);
//        result.addDefaultModel("templetList", templetList);
        return result;
    }

    public Result detail(Templet templet) {
        Result result = new Result();
        if (templet == null) {
            return result;
        }
        result.setSuccess(true);
        templet = templetDao.queryForObject(templet);
        if (templet == null) {
            return result;
        }
        result.addDefaultModel("templet", templet);

        return result;
    }

    public Result insert(Templet templet) {
        Result result = new Result();
        if (templet == null) {
            result.setSuccess(false);
            result.setResultCode("system.no.entity.to.operate");
            return result;
        }
        Long id = templetDao.insert(templet);
        if (id <= 0) {
            result.setSuccess(false);
            result.setResultCode("system.insert.error");
        } else {
            result.setSuccess(true);
            result.setResultCode("system.insert.success");
        }
        return result;
    }

    public Result update(Templet templet) {
        Result result = new Result();
        if (templet == null || templet.getId() == null || templet.getId() <= 0) {
            result.setSuccess(false);
            result.setResultCode("system.no.entity.to.operate");
            return result;
        }
//        boolean success = templetDao.update(templet);
//        result.setSuccess(success);
//        if(success){
//            result.setResultCode("system.update.success");
//        } else {
//            result.setResultCode("system.update.success");
//        }
        return result;
    }

    public Result delete(Templet templet) {
        Result result = new Result();
        if (templet == null || templet.getId() == null || templet.getId() <= 0) {
            result.setSuccess(false);
            result.setResultCode("system.no.entity.to.operate");
            return result;
        }
//        boolean success = templetDao.delete(templet);
//        result.setSuccess(success);
//        if(success){
//            result.setResultCode("system.delete.success");
//        } else {
//            result.setResultCode("system.delete.error");
//        }
        return result;
    }
}
