package com.jd.help.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * Catalog domain??
 * <p/>
 * generated by bud
 *
 * @author @laichendong
 */
@SuppressWarnings("unused")
public class CatalogBO implements Serializable {

    /**
     * ????ID
     */
    private Integer id;

    /**
     * ???
     */
    private String name;
    
    /**
     * 
     */
    private Integer pid;
    /**
     * ×Ó½ÚµãList
     */
    private List<CatalogBO> children;
    
    /**
     * 
     */
    private Integer level;
    /**
     * ??
     */
    private Byte status;

    /**
     * ???
     */
    private String notes;

    /**
     * ???????
     */
    private Integer sortOrder;

    /**
     * ??????
     */
    private String creator;

    /**
     * ?????
     */
    private String modifier;

    /**
     * ???????
     */
    private Date created;

    /**
     * ??????
     */
    private Date modified;

    /**
     *
     */
    private Integer siteId;

    public CatalogBO() {

    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<CatalogBO> getChildren() {
		return children;
	}

	public void setChildren(List<CatalogBO> children) {
		this.children = children;
	}

	public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Integer getSortOrder() {
        return this.sortOrder;
    }

    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    public String getCreator() {
        return this.creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public String getModifier() {
        return this.modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Date getModified() {
        return this.modified;
    }

    public void setModified(Date modified) {
        this.modified = modified;
    }

    public Integer getSiteId() {
        return siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

	public Integer getLevel() {
		return level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Integer getPid() {
		return pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}
    
}