package com.jd.help.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * HotIssue domain类
 * <p/>
 * generated by bud
 *
 * @author @laichendong
 */
@SuppressWarnings("unused")
public class HotIssue implements Serializable {

    /**
     * 主键ID
     */
    private Integer id;

    /**
     * 名称
     */
    private String name;

    /**
     * 链接
     */
    private String link;

    /**
     * 问题ID
     */
    private Integer issueId;

    /**
     * 排序字段
     */
    private Integer sortOrder;

    /**
     *
     */
    private Date created;

    /**
     *
     */
    private Date modified;


    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLink() {
        return this.link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public Integer getIssueId() {
        return this.issueId;
    }

    public void setIssueId(Integer issueId) {
        this.issueId = issueId;
    }

    public Integer getSortOrder() {
        return this.sortOrder;
    }

    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Date getModified() {
        return this.modified;
    }

    public void setModified(Date modified) {
        this.modified = modified;
    }


}