package com.jd.help.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * IssueAnswer domain类
 * <p/>
 * generated by bud
 *
 * @author @laichendong
 */
@SuppressWarnings("unused")
public class IssueAnswer implements Serializable {

    /**
     * 问题ID
     */
    private Integer issueId;

    /**
     * 答案
     */
    private String answer;

    /**
     *
     */
    private Date created;

    /**
     *
     */
    private Date modified;


    public Integer getIssueId() {
        return this.issueId;
    }

    public void setIssueId(Integer issueId) {
        this.issueId = issueId;
    }

    public String getAnswer() {
        return this.answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Date getModified() {
        return this.modified;
    }

    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * 移除content里 href的http:
     */
    public void removeHttp(){
        if (this.answer != null) {
            this.answer = HttpsUtil.removeHttp(this.answer);
        }
    }
}