package com.jd.help.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * IssueTemp domain类
 * <p/>
 * generated by bud
 *
 * @author @laichendong
 */
@SuppressWarnings("unused")
public class IssueTemp implements Serializable {

    /**
     * 问题ID
     */
    private Integer issueId;

    /**
     * 模板ID
     */
    private Integer tempId;

    /**
     *
     */
    private Date created;

    /**
     *
     */
    private Date modified;


    public Integer getIssueId() {
        return this.issueId;
    }

    public void setIssueId(Integer issueId) {
        this.issueId = issueId;
    }

    public Integer getTempId() {
        return this.tempId;
    }

    public void setTempId(Integer tempId) {
        this.tempId = tempId;
    }

    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Date getModified() {
        return this.modified;
    }

    public void setModified(Date modified) {
        this.modified = modified;
    }


}