package com.jd.help.domain;

import com.jd.help.domain.knowledge.KnowledgeVO;

import java.io.Serializable;
import java.util.List;

/**
 * Issue domain¿‡
 * <p/>
 * generated by bud
 *
 * @author @laichendong
 */
@SuppressWarnings("unused")
public class IssueBO implements Serializable {
	
	private Issue issue;
	
	private IssueAnswer issueAnswer;
	
	private List<IssueOldNewMapping> oldNewMappingList;

	private List<IssueRel> issueRelList;

	private List<ScenesButtonRel> scenesButtonRelList;

	private IssueDateQuery issueDateQuery;

	private List<KnowledgeVO> relationKnowledgeList;
	
	public Issue getIssue() {
		return issue;
	}

	public void setIssue(Issue issue) {
		this.issue = issue;
	}

	public IssueAnswer getIssueAnswer() {
		return issueAnswer;
	}

	public void setIssueAnswer(IssueAnswer issueAnswer) {
		this.issueAnswer = issueAnswer;
	}

	public List<IssueOldNewMapping> getOldNewMappingList() {
		return oldNewMappingList;
	}

	public void setOldNewMappingList(List<IssueOldNewMapping> oldNewMappingList) {
		this.oldNewMappingList = oldNewMappingList;
	}

	public List<IssueRel> getIssueRelList() {
		return issueRelList;
	}

	public void setIssueRelList(List<IssueRel> issueRelList) {
		this.issueRelList = issueRelList;
	}

	public List<ScenesButtonRel> getScenesButtonRelList() {
		return scenesButtonRelList;
	}

	public void setScenesButtonRelList(List<ScenesButtonRel> scenesButtonRelList) {
		this.scenesButtonRelList = scenesButtonRelList;
	}

	public IssueDateQuery getIssueDateQuery() {
		return issueDateQuery;
	}

	public void setIssueDateQuery(IssueDateQuery issueDateQuery) {
		this.issueDateQuery = issueDateQuery;
	}

	public List<KnowledgeVO> getRelationKnowledgeList() {
		return relationKnowledgeList;
	}

	public void setRelationKnowledgeList(List<KnowledgeVO> relationKnowledgeList) {
		this.relationKnowledgeList = relationKnowledgeList;
	}
}