package com.jd.help.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * IssueRel domain类
 * <p/>
 * generated by bud
 *
 * @author @laichendong
 */
@SuppressWarnings("unused")
public class IssueRel implements Serializable {

    /**
     * 主键ID
     */
    private Integer id;

    /**
     * 所属问题ID
     */
    private Integer issueId;

    /**
     * 相关问题标题
     */
    private String relIssueTitle;

    /**
     * 相关问题链接
     */
    private String relIssueLink;

    /**
     *
     */
    private Date created;

    /**
     *
     */
    private Date modified;


    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIssueId() {
        return this.issueId;
    }

    public void setIssueId(Integer issueId) {
        this.issueId = issueId;
    }


    public String getRelIssueTitle() {
		return relIssueTitle;
	}

	public void setRelIssueTitle(String relIssueTitle) {
		this.relIssueTitle = relIssueTitle;
	}

	public String getRelIssueLink() {
		return relIssueLink;
	}

	public void setRelIssueLink(String relIssueLink) {
		this.relIssueLink = relIssueLink;
	}

	public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Date getModified() {
        return this.modified;
    }

    public void setModified(Date modified) {
        this.modified = modified;
    }


}