package com.jd.help.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * Templet domain类
 * <p/>
 * generated by bud
 *
 * @author @laichendong
 */
@SuppressWarnings("unused")
public class Templet implements Serializable {

    /**
     * 主键ID
     */
    private Integer id;

    /**
     * 模板名称
     */
    private String name;

    /**
     * 模板对应程序文件名称
     */
    private String fileName;

    /**
     *
     */
    private Date created;

    /**
     *
     */
    private Date modified;


    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Date getModified() {
        return this.modified;
    }

    public void setModified(Date modified) {
        this.modified = modified;
    }


}