package com.jd.help.dao;

import com.jd.help.domain.Catalog;

import java.util.List;

/**
 * dao 接口
 * generated by bud
 *
 * @author @laichendong
 */
public interface CatalogDao {

    /**
     * 插入catalog对象到数据库
     *
     * @param catalog 待插入的对象
     * @return 是否插入成功
     */
    long insert(Catalog catalog);

    /**
     * 从数据库删除catalog对象
     * 软删除，只是update状态，不delete数据行
     *
     * @param catalog 删除条件对象，通常，指定主键字段的值来删除一条记录，或指定其他字段删除一组记录。
     * @return 删除的行数
     */
    int delete(Catalog catalog);

    /**
     * 更新catalog对象到数据库
     *
     * @param catalog 待更新的对象，通常，需要更新那些字段就指定哪些字段的值，但主键字段一定需要指定。
     * @return 更新的行数
     */
    int update(Catalog catalog);

    /**
     * 更新catalog对象到数据库
     *
     * @param catalog 待更新的对象，通常，需要更新那些字段就指定哪些字段的值，但主键字段一定需要指定。
     * @return 更新的行数
     */
    int updateCatalog(Catalog catalog) ;

    /**
     * 更新catalog对象状态
     * @param catalog 待更新的对象，通常，需要更新那些字段就指定哪些字段的值，但主键字段一定需要指定。
     * @return 更新的行数
     */
    int updateCatalogStatus(Catalog catalog) ;

    /**
     * 更新catalog对象排序值
     * @param catalog 待更新的对象，通常，需要更新那些字段就指定哪些字段的值，但主键字段一定需要指定。
     * @return 更新的行数
     */
    int updateCatalogSortOrder(Catalog catalog) ;

    /**
     * 从数据库查询一个catalog对象
     *
     * @param catalog 查询条件对象，通常指定主键字段的值
     * @return 有则返回对象，无则返回null
     */
    Catalog queryForObject(Catalog catalog);

    /**
     * 根据条件查询满足条件的catalog对象个数
     *
     * @param catalog 查询条件
     * @return 记录数
     */
    int queryForCount(Catalog catalog);

    /**
     * 根据条件查询满足条件的catalog的最大排序值
     *
     * @param catalog 查询条件
     * @return 记录数
     */
    Integer getMaxSortOrder(Catalog catalog);

    /**
     * 根据条件查询满足条件的catalog对象列表
     *
     * @param catalog 查询条件
     * @return 满足条件的catalog对象列表，没有满足条件的catalog对象，则返回null
     */
    List<Catalog> queryForList(Catalog catalog, int page, int pageSize);

    /**
     * 根据条件查询满足条件的catalog对象列表
     *
     * @param catalog 查询条件
     * @return 满足条件的catalog对象列表，没有满足条件的catalog对象，则返回null
     */
    List<Catalog> queryForList(Catalog catalog) ;
    
    /**
     * 跟据条件查询启用类目
     * @param catalog
     * @return
     */
    List<Catalog> getLeftMenuCatalog(Catalog catalog);
    
    /**
     * 跟据pid查询三级类目
     * @param catalog
     * @return
     */
    List<Catalog> getCatalogLevel3List(Catalog catalog);

    /**
     * 查询所有类目
     * @param catalog
     * @return
     */
    List<Catalog> getAllLeftMenuCatalog(Catalog catalog);

}
