package com.jd.help.dao;

import com.jd.help.domain.HotWord;

import java.util.List;

/**
 * dao 接口
 * generated by bud
 *
 * @author @laichendong
 */
public interface HotWordDao {

    /**
     * 插入hotWord对象到数据库
     *
     * @param hotWord 待插入的对象
     * @return 是否插入成功
     */
    long insert(HotWord hotWord);

    /**
     * 从数据库删除hotWord对象
     * 软删除，只是update状态，不delete数据行
     *
     * @param hotWord 删除条件对象，通常，指定主键字段的值来删除一条记录，或指定其他字段删除一组记录。
     * @return 删除的行数
     */
    int delete(HotWord hotWord);

    /**
     * 更新hotWord对象到数据库
     *
     * @param hotWord 待更新的对象，通常，需要更新那些字段就指定哪些字段的值，但主键字段一定需要指定。
     * @return 更新的行数
     */
    int update(HotWord hotWord);

    /**
     * 从数据库查询一个hotWord对象
     *
     * @param hotWord 查询条件对象，通常指定主键字段的值
     * @return 有则返回对象，无则返回null
     */
    HotWord queryForObject(HotWord hotWord);

    /**
     * 根据条件查询满足条件的hotWord对象个数
     *
     * @return 记录数
     */
    int queryForCount(HotWord hotWord);

    /**
     * 根据条件查询满足条件的hotWord对象列表
     *
     * @return 满足条件的hotWord对象列表，没有满足条件的hotWord对象，则返回null
     */
    List<HotWord> queryForList(HotWord hotWord, int page, int pageSize);

}
