package com.jd.help.dao;

import com.jd.help.domain.IssueRel;

import java.util.List;

/**
 * dao 接口
 * generated by bud
 *
 * @author @laichendong
 */
public interface IssueRelDao {

    /**
     * 插入issueRel对象到数据库
     *
     * @param issueRel 待插入的对象
     * @return 是否插入成功
     */
	void insert(List<IssueRel> issueRelList);

    /**
     * 从数据库删除issueRel对象
     *
     * @return 删除的行数
     */
    int delete(int issueId);

    /**
     * 更新issueRel对象到数据库
     *
     * @param issueRel 待更新的对象，通常，需要更新那些字段就指定哪些字段的值，但主键字段一定需要指定。
     * @return 更新的行数
     */
    int update(IssueRel issueRel);

    /**
     * 从数据库查询一个issueRel对象
     *
     * @param issueRel 查询条件对象，通常指定主键字段的值
     * @return 有则返回对象，无则返回null
     */
    IssueRel queryForObject(IssueRel issueRel);

    /**
     * 根据条件查询满足条件的issueRel对象个数
     *
     * @return 记录数
     */
    int queryForCount(IssueRel issueRel);

    /**
     * 根据条件查询满足条件的issueRel对象列表
     *
     * @return 满足条件的issueRel对象列表，没有满足条件的issueRel对象，则返回null
     */
    List<IssueRel> queryForList(IssueRel issueRel, int page, int pageSize);
    
    /**
     * 更加issueId查询
     * @param issueId
     * @return
     */
    List<IssueRel> queryForListByIssueId(int issueId);

}
