package com.jd.help.dao;

import com.jd.help.domain.Issue;
import com.jd.help.domain.IssueQuery;

import java.util.List;

/**
 * dao 接口
 * generated by bud
 *
 * @author @laichendong
 */
public interface IssueDao {

    /**
     * 插入issue对象到数据库
     *
     * @param issue 待插入的对象
     * @return 是否插入成功
     */
    long insert(Issue issue);

    /**
     * 从数据库删除issue对象
     * 软删除，只是update状态，不delete数据行
     *
     * @param issue 删除条件对象，通常，指定主键字段的值来删除一条记录，或指定其他字段删除一组记录。
     * @return 删除的行数
     */
    int delete(Issue issue);

    /**
     * 更新issue对象到数据库
     *
     * @param issue 待更新的对象，通常，需要更新那些字段就指定哪些字段的值，但主键字段一定需要指定。
     * @return 更新的行数
     */
    int update(Issue issue);

    /**
     * 从数据库查询一个issue对象
     *
     * @param issue 查询条件对象，通常指定主键字段的值
     * @return 有则返回对象，无则返回null
     */
    Issue queryForObject(Issue issue);

    /**
     * 根据条件查询满足条件的issue对象个数
     *
     * @return 记录数
     */
    int queryForCount(Issue issue);

    /**
     * 根据条件查询满足条件的issue对象列表
     *
     * @return 满足条件的issue对象列表，没有满足条件的issue对象，则返回null
     */
    List<Issue> queryForList(Issue issue, int page, int pageSize);

    int queryTotalCount(IssueQuery issueQuery);

    List<Issue> queryForIssueList(IssueQuery issueQuery, int page, int pageSize);

    int updateStatus(Issue issue);
    /**
     * 更新订单的各个状态
     * @param issue
     * @return
     */
    int updateOrderStatus(Issue issue);
    
    /**
     * 根据类目ID查询上线的问题列表
     * @param issue
     * @return
     */
    List<Issue> queryOnlineList(Issue issue);
    
    /**
     * 清除所有订单关联
     */
    void deleteOrderStatus();


    List<Integer> query4Issue2Es(IssueQuery issueQuery);
}
