package com.jd.help.dao;

import com.jd.help.domain.SelfMenu;

import java.util.List;

/**
 * dao 接口
 * generated by bud
 *
 * @author @laichendong
 */
public interface SelfMenuDao {

    /**
     * 插入selfMenu对象到数据库
     *
     * @param selfMenu 待插入的对象
     * @return 是否插入成功
     */
    long insert(SelfMenu selfMenu);

    /**
     * 从数据库删除selfMenu对象
     * 软删除，只是update状态，不delete数据行
     *
     * @param selfMenu 删除条件对象，通常，指定主键字段的值来删除一条记录，或指定其他字段删除一组记录。
     * @return 删除的行数
     */
    int delete(SelfMenu selfMenu);

    /**
     * 更新selfMenu对象到数据库
     *
     * @param selfMenu 待更新的对象，通常，需要更新那些字段就指定哪些字段的值，但主键字段一定需要指定。
     * @return 更新的行数
     */
    int update(SelfMenu selfMenu);

    /**
     * 从数据库查询一个selfMenu对象
     *
     * @param selfMenu 查询条件对象，通常指定主键字段的值
     * @return 有则返回对象，无则返回null
     */
    SelfMenu queryForObject(SelfMenu selfMenu);

    /**
     * 根据条件查询满足条件的selfMenu对象个数
     *
     * @return 记录数
     */
    int queryForCount(SelfMenu selfMenu);

    /**
     * 根据条件查询满足条件的selfMenu对象列表
     *
     * @return 满足条件的selfMenu对象列表，没有满足条件的selfMenu对象，则返回null
     */
    List<SelfMenu> queryForList(SelfMenu selfMenu, int page, int pageSize);

}
