package com.jd.help.dao;

import com.jd.help.domain.Site;

import java.util.List;

/**
 * dao 接口
 * generated by bud
 *
 * @author @laichendong
 */
public interface SiteDao {

    /**
     * 插入site对象到数据库
     *
     * @param site 待插入的对象
     * @return 是否插入成功
     */
    long insert(Site site);

    /**
     * 从数据库删除site对象
     * 软删除，只是update状态，不delete数据行
     *
     * @param site 删除条件对象，通常，指定主键字段的值来删除一条记录，或指定其他字段删除一组记录。
     * @return 删除的行数
     */
    int delete(Site site);

    /**
     * 更新site对象到数据库
     *
     * @param site 待更新的对象，通常，需要更新那些字段就指定哪些字段的值，但主键字段一定需要指定。
     * @return 更新的行数
     */
    int update(Site site);


    /**
     * 根据条件查询满足条件的site对象个数
     *
     * @return 记录数
     */
    int queryForCount(Site site);

    /**
     * 根据条件查询满足条件的site对象列表
     *
     * @return 满足条件的site对象列表，没有满足条件的site对象，则返回null
     */
    List<Site> queryForList(Site site, int page, int pageSize);
    
    /**
     * 查询所有的site对象列表
     *
     * @return 
     */
    List<Site> queryAllForList();
    
    /**
     * 通过ID查询site对象
     *
     * @return 
     */
    Site findOne(Site site);

    Site findDefaultSite();

    int updateEnName(Site site);

}
