package com.jd.help.service;


import com.jd.common.web.result.Result;
import com.jd.help.domain.Catalog;

/**
 * Catalog service 锟接匡拷
 * generated by bud
 *
 * @author @laichendong
 */
public interface CatalogService {
    Result list(Catalog catalog, int page, int pageSize);

    Result detail(Catalog catalog);

    Result insert(Catalog catalog);

    Result updateSortOrder(Catalog catalog, Catalog refCatalog);

    Result update(Catalog catalog);

    Result updateCatalog(Catalog catalog);

    Result updateCatalogStatus(Catalog catalog);

    Result delete(Catalog catalog);
    /**
     * 根据siteID查询一级类目的数量
     * @param catalog
     * @return
     */
    Result getFirstCatCountBySid(Catalog catalog);
    /**
     * 根据siteId和pid查询类目 不分页
     * @param catalog
     * @return
     */
    public Result listAllByPidAndSiteId(Catalog catalog);
    
    Result listAllBySiteId(Catalog catalog);
    /**
     * 查询左侧菜单
     * @param catalog
     * @return
     */
    Result getLeftMenuCatalog(Catalog catalog);
    
    /**
     * 根据pid查询三级类目
     * @param catalog
     * @return
     */
    Result getCatalogLevel3List(Catalog catalog);

    /**
     * 查询1,2,3级左侧菜单
     * @param catalog
     * @return
     */
    Result getAllLeftMenuCatalog(Catalog catalog);
    
    Catalog getCatalogById(Integer cataId);
}