package com.jd.help.service;

import com.jd.common.web.result.Result;
import com.jd.help.domain.HotWord;

/**
 * HotWord service ½Ó¿Ú
 * generated by bud
 *
 * @author @laichendong
 */
public interface HotWordService {
    Result list(HotWord hotWord, int page, int pageSize);

    Result detail(HotWord hotWord);

    Result insert(HotWord hotWord);

    Result update(HotWord hotWord);

    Result delete(HotWord hotWord);
}