package com.jd.help.service;

import com.jd.common.util.PaginatedList;
import com.jd.common.web.result.Result;
import com.jd.help.domain.Issue;
import com.jd.help.domain.IssueBO;
import com.jd.help.domain.IssueQuery;

/**
 * Issue service 接口
 * generated by bud
 *
 * @author @laichendong
 */
public interface IssueService {
    PaginatedList<Issue> list(IssueQuery issueQuery, int page, int pageSize);

    Result detail(Issue issue);

    Result insert(IssueBO issueBO);

    Result update(IssueBO issueBO);

    Result delete(Issue issue);

    /**
     * 修改问题状态
     *
     * @param issue
     * @return
     */
    Result updateStatus(Issue issue);
    
    /**
     * 用于前台
     * 通过issueID查询IssueBO
     * @param issueBO
     * @param needRemoveHttp
     * @return
     */
    Result queryIssueBOByIssueId(IssueBO issueBO, boolean needRemoveHttp);

    /**
     * 用于后台
     * 通过issueID查询IssueBO
     * @param issueBO
     * @param needRemoveHttp
     * @return
     */
    Result queryIssueBOByIssueId2(IssueBO issueBO, boolean needRemoveHttp);
    
    /**
     * 更新订单的各个状态
     * @param issue
     * @return
     */
    Result updateOrderStatus(Issue issue);
    
    /**
     * 根据类目ID查询上线的问题列表
     * @param issue
     * @return
     */
    Result findOnlineList(Issue issue);
    
    /**
     * 清除所有订单关联
     */
    
    void deleteOrderStatus();

    /**
     * 用于后台
     * 根据id查文章
     * @param issueId
     * @return
     */
    Issue queryById(Integer issueId);
}