package com.jd.help.service;

import com.jd.common.web.result.Result;
import com.jd.help.domain.SelfMenu;

/**
 * SelfMenu service ½Ó¿Ú
 * generated by bud
 *
 * @author @laichendong
 */
public interface SelfMenuService {
    Result list(SelfMenu selfMenu, int page, int pageSize);

    Result detail(SelfMenu selfMenu);

    Result insert(SelfMenu selfMenu);

    Result update(SelfMenu selfMenu);

    Result delete(SelfMenu selfMenu);
}