package com.jd.help.service;

import com.jd.common.web.result.Result;
import com.jd.help.domain.Site;

/**
 * Site service 接口
 * generated by bud
 *
 * @author @laichendong
 */
public interface SiteService {
    Result list(Site site, int page, int pageSize);

    Result insert(Site site);

    Result update(Site site);

    Result delete(Site site);
    
    /**
     * 查询所有的site对象列表
     *
     * @return 
     */
    Result listAll();
    
    /**
     * 通过ID查询site对象
     *
     * @return 
     */
    Result findOne(Site site);

    /**
     * 查找默认站点
     *
     * @return
     */
    Result findDefaultSite();
}