package com.jd.help.service;

import com.jd.common.web.result.Result;
import com.jd.help.domain.Templet;

/**
 * Templet service ½Ó¿Ú
 * generated by bud
 *
 * @author @laichendong
 */
public interface TempletService {
    Result list(Templet templet, int page, int pageSize);

    Result detail(Templet templet);

    Result insert(Templet templet);

    Result update(Templet templet);

    Result delete(Templet templet);
}