package com.jd.help.dao.impl;

import com.jd.common.dao.BaseDao;
import com.jd.help.dao.HotWordDao;
import com.jd.help.dao.util.Page;
import com.jd.help.domain.HotWord;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.dao.DataAccessException;
import org.springframework.stereotype.Repository;

import javax.annotation.Resource;
import javax.sql.DataSource;
import java.util.List;

/**
 * HotWord dao实现
 * generated by bud
 *
 * @author @laichendong
 */
@Repository("hotWordDao")
@SuppressWarnings("unused")
public class HotWordDaoImpl extends BaseDao implements HotWordDao {

    private final static Log logger = LogFactory.getLog(HotWordDaoImpl.class);

    /**
     * 注入数据源
     */
    @Override
    @Resource(name = "helpCenterDataSource")
    public void setDataSource(DataSource dataSource) {
        super.setDataSource(dataSource);
    }


    public long insert(HotWord hotWord) {
        return (Long) insert("HotWord.insert", hotWord);
    }

    public int delete(HotWord hotWord) {
        return update("HotWord.delete", hotWord);
    }

    public int update(HotWord hotWord) {
        return update("HotWord.update", hotWord);
    }

    public HotWord queryForObject(HotWord hotWord) {
        try {
            return (HotWord) queryForObject("HotWord.queryForObject", hotWord);
        } catch (DataAccessException e) {
            logger.error("数据库访问出错！", e);
            return null;
        }
    }

    public int queryForCount(HotWord hotWord) {
        return (Integer) queryForObject("HotWord.queryForCount", hotWord);
    }

    @SuppressWarnings("unchecked")
    public List<HotWord> queryForList(HotWord hotWord, int page, int pageSize) {
        Page<HotWord> condition = new Page<HotWord>();
        condition.setModel(hotWord);
        condition.setPage(page);
        condition.setPageSize(pageSize);
        return queryForList("HotWord.queryForList", condition);
    }

}
