package com.jd.help.dao.impl;

import com.jd.common.dao.BaseDao;
import com.jd.help.dao.IssueRelDao;
import com.jd.help.dao.util.Page;
import com.jd.help.domain.IssueRel;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.dao.DataAccessException;
import org.springframework.stereotype.Repository;

import javax.annotation.Resource;
import javax.sql.DataSource;
import java.util.List;

/**
 * IssueRel dao实现
 * generated by bud
 *
 * @author @laichendong
 */
@Repository("issueRelDao")
@SuppressWarnings("unused")
public class IssueRelDaoImpl extends BaseDao implements IssueRelDao {

    private final static Log logger = LogFactory.getLog(IssueRelDaoImpl.class);

    /**
     * 注入数据源
     */
    @Override
    @Resource(name = "helpCenterDataSource")
    public void setDataSource(DataSource dataSource) {
        super.setDataSource(dataSource);
    }


    public void insert(List<IssueRel> issueRelList) {
        insert("IssueRel.insert", issueRelList);
    }

    public int delete(int issueId) {
        return delete("IssueRel.delete", issueId);
    }

    public int update(IssueRel issueRel) {
        return update("IssueRel.update", issueRel);
    }

    public IssueRel queryForObject(IssueRel issueRel) {
        try {
            return (IssueRel) queryForObject("IssueRel.queryForObject", issueRel);
        } catch (DataAccessException e) {
            logger.error("数据库访问出错！", e);
            return null;
        }
    }

    public int queryForCount(IssueRel issueRel) {
        return (Integer) queryForObject("IssueRel.queryForCount", issueRel);
    }

    @SuppressWarnings("unchecked")
    public List<IssueRel> queryForList(IssueRel issueRel, int page, int pageSize) {
        Page<IssueRel> condition = new Page<IssueRel>();
        condition.setModel(issueRel);
        condition.setPage(page);
        condition.setPageSize(pageSize);
        return queryForList("IssueRel.queryForList", condition);
    }
    @SuppressWarnings("unchecked")
    public List<IssueRel> queryForListByIssueId(int issueId){
    	 try {
             return queryForList("IssueRel.queryForListByIssueId", issueId);
         } catch (DataAccessException e) {
             logger.error("数据库访问出错！", e);
             return null;
         }
    }
}
