package com.jd.help.dao.impl;

import com.jd.common.dao.BaseDao;
import com.jd.help.dao.IssueAnswerDao;
import com.jd.help.dao.util.Page;
import com.jd.help.domain.IssueAnswer;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.dao.DataAccessException;
import org.springframework.stereotype.Repository;

import javax.annotation.Resource;
import javax.sql.DataSource;
import java.util.List;

/**
 * IssueAnswer dao实现
 * generated by bud
 *
 * @author @laichendong
 */
@Repository("issueAnswerDao")
@SuppressWarnings("unused")
public class IssueAnswerDaoImpl extends BaseDao implements IssueAnswerDao {

    private final static Log logger = LogFactory.getLog(IssueAnswerDaoImpl.class);

    /**
     * 注入数据源
     */
    @Override
    @Resource(name = "helpCenterDataSource")
    public void setDataSource(DataSource dataSource) {
        super.setDataSource(dataSource);
    }


    public void insert(IssueAnswer issueAnswer) {
        insert("IssueAnswer.insert", issueAnswer);
    }

    public int delete(IssueAnswer issueAnswer) {
        return update("IssueAnswer.delete", issueAnswer);
    }

    public int update(IssueAnswer issueAnswer) {
        return update("IssueAnswer.update", issueAnswer);
    }

    public IssueAnswer queryForObject(IssueAnswer issueAnswer) {
        try {
            return (IssueAnswer) queryForObject("IssueAnswer.queryForObject", issueAnswer);
        } catch (DataAccessException e) {
            logger.error("数据库访问出错！", e);
            return null;
        }
    }

    public int queryForCount(IssueAnswer issueAnswer) {
        return (Integer) queryForObject("IssueAnswer.queryForCount", issueAnswer);
    }

    @SuppressWarnings("unchecked")
    public List<IssueAnswer> queryForList(IssueAnswer issueAnswer, int page, int pageSize) {
        Page<IssueAnswer> condition = new Page<IssueAnswer>();
        condition.setModel(issueAnswer);
        condition.setPage(page);
        condition.setPageSize(pageSize);
        return queryForList("IssueAnswer.queryForList", condition);
    }

    public IssueAnswer queryOneByIssueId(int issueId){
    	 try {
             return (IssueAnswer) queryForObject("IssueAnswer.queryOneByIssueId", issueId);
         } catch (DataAccessException e) {
             logger.error("数据库访问出错！", e);
             return null;
         }
    }
}
