package com.jd.help.dao.impl;

import com.jd.common.dao.BaseDao;
import com.jd.help.dao.SelfMenuDao;
import com.jd.help.dao.util.Page;
import com.jd.help.domain.SelfMenu;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.dao.DataAccessException;
import org.springframework.stereotype.Repository;

import javax.annotation.Resource;
import javax.sql.DataSource;
import java.util.List;

/**
 * SelfMenu dao实现
 * generated by bud
 *
 * @author @laichendong
 */
@Repository("selfMenuDao")
@SuppressWarnings("unused")
public class SelfMenuDaoImpl extends BaseDao implements SelfMenuDao {

    private final static Log logger = LogFactory.getLog(SelfMenuDaoImpl.class);

    /**
     * 注入数据源
     */
    @Override
    @Resource(name = "helpCenterDataSource")
    public void setDataSource(DataSource dataSource) {
        super.setDataSource(dataSource);
    }


    public long insert(SelfMenu selfMenu) {
        return (Long) insert("SelfMenu.insert", selfMenu);
    }

    public int delete(SelfMenu selfMenu) {
        return update("SelfMenu.delete", selfMenu);
    }

    public int update(SelfMenu selfMenu) {
        return update("SelfMenu.update", selfMenu);
    }

    public SelfMenu queryForObject(SelfMenu selfMenu) {
        try {
            return (SelfMenu) queryForObject("SelfMenu.queryForObject", selfMenu);
        } catch (DataAccessException e) {
            logger.error("数据库访问出错！", e);
            return null;
        }
    }

    public int queryForCount(SelfMenu selfMenu) {
        return (Integer) queryForObject("SelfMenu.queryForCount", selfMenu);
    }

    @SuppressWarnings("unchecked")
    public List<SelfMenu> queryForList(SelfMenu selfMenu, int page, int pageSize) {
        Page<SelfMenu> condition = new Page<SelfMenu>();
        condition.setModel(selfMenu);
        condition.setPage(page);
        condition.setPageSize(pageSize);
        return queryForList("SelfMenu.queryForList", condition);
    }

}
