package com.jd.help.dao.impl;

import com.jd.common.dao.BaseDao;
import com.jd.help.dao.TempletDao;
import com.jd.help.dao.util.Page;
import com.jd.help.domain.Templet;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.dao.DataAccessException;
import org.springframework.stereotype.Repository;

import javax.annotation.Resource;
import javax.sql.DataSource;
import java.util.List;

/**
 * Templet dao实现
 * generated by bud
 *
 * @author @laichendong
 */
@Repository("templetDao")
@SuppressWarnings("unused")
public class TempletDaoImpl extends BaseDao implements TempletDao {

    private final static Log logger = LogFactory.getLog(TempletDaoImpl.class);

    /**
     * 注入数据源
     */
    @Override
    @Resource(name = "helpCenterDataSource")
    public void setDataSource(DataSource dataSource) {
        super.setDataSource(dataSource);
    }


    public long insert(Templet templet) {
        return (Long) insert("Templet.insert", templet);
    }

    public int delete(Templet templet) {
        return update("Templet.delete", templet);
    }

    public int update(Templet templet) {
        return update("Templet.update", templet);
    }

    public Templet queryForObject(Templet templet) {
        try {
            return (Templet) queryForObject("Templet.queryForObject", templet);
        } catch (DataAccessException e) {
            logger.error("数据库访问出错！", e);
            return null;
        }
    }

    public int queryForCount(Templet templet) {
        return (Integer) queryForObject("Templet.queryForCount", templet);
    }

    @SuppressWarnings("unchecked")
    public List<Templet> queryForList(Templet templet, int page, int pageSize) {
        Page<Templet> condition = new Page<Templet>();
        condition.setModel(templet);
        condition.setPage(page);
        condition.setPageSize(pageSize);
        return queryForList("Templet.queryForList", condition);
    }

}
